ci: Try workaround for greenlet issue
  Attempting uninstall: greenlet
    Found existing installation: greenlet 0.4.13
error: uninstall-distutils-installed-package

× Cannot uninstall greenlet 0.4.13
╰─> It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.